apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: b-system-trigger-combined-app2
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: b-system-trigger-combined-app2
